/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.flic;

import io.flic.lib.FlicAppNotInstalledException;
import io.flic.lib.FlicBroadcastReceiverFlags;
import io.flic.lib.FlicButton;
import io.flic.lib.FlicManager;
import io.flic.lib.FlicManagerInitializedCallback;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiActivityResultHandler;
import org.appcelerator.kroll.common.Log;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;

@Kroll.module(name = "Flic", id = "ti.flic")
public class FlicModule extends KrollModule implements TiActivityResultHandler {

	// Standard Debugging variables
	private static final String LCAT = "FlicModule";
	private Context ctx;
	private String appId;
	private String appSecret;
	private String appName;

	public FlicModule() {
		super();
		ctx = TiApplication.getInstance();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is
		// created
	}

	@Kroll.method
	public void Init(KrollDict opts) {
		if (opts.containsKeyAndNotNull("appId")) {
			appId = opts.getString("appId");
		}
		if (opts.containsKeyAndNotNull("appSecret")) {
			appId = opts.getString("appSecret");
		}
		if (opts.containsKeyAndNotNull("appName")) {
			appId = opts.getString("appName");
		}
		try {
			FlicManager.getInstance(ctx, new FlicManagerInitializedCallback() {
				@Override
				public void onInitialized(FlicManager manager) {
				}
			});
		} catch (FlicAppNotInstalledException err) {
			Log.e(LCAT, "Flic App is not installed");
		}
	}

	@Override
	public void onResult(Activity activity, final int requestCode,
			final int resultCode, final Intent data) {
		FlicManager.getInstance(ctx, new FlicManagerInitializedCallback() {
			@Override
			public void onInitialized(FlicManager manager) {
				FlicButton button = manager.completeGrabButton(requestCode,
						resultCode, data);
				if (button != null) {
					button.registerListenForBroadcast(FlicBroadcastReceiverFlags.UP_OR_DOWN
							| FlicBroadcastReceiverFlags.REMOVED);
					// Toast.makeText(MainActivity.this, "Grabbed a button",
					// Toast.LENGTH_SHORT).show();
				} else {
					// Toast.makeText(MainActivity.this,
					// "Did not grab any button", Toast.LENGTH_SHORT).show();
				}
			}
		});
	}

	@Override
	public void onError(Activity arg0, int arg1, Exception arg2) {
	}

}
